### ISSUE TITLE
the >>blockwords command will be automatically deleted after it passes, due to the command containing a blocked word.

### ISSUE THREAD

**Issue by zaxer2** [aurora-pro/apex-sigma-core#4]
for example. 
You type >>blockword poopoo
Sigma responds with "1 word added to blocked words list"
your message is deleted
Sigma PMs you with "1 message was deleted for containing a blocked word"

So now other admins can't see what words I'm blocking, and have to use >>blockedwords to access the list.

**Comment by AXAz0r** [comment]
Issue fixed in commit `c56b9f429d5b8f1b59b8cde43f656318c491fcc7`.
Filter will not delete commands containing filtered words to help with moderation clarity.
